### ISSUE TITLE
Cannot open Appointment page

### ISSUE THREAD

**Issue by arjunkn** [manuvarghese236/dnt#2]
Trying to get property of non-object. [on clicking appointment link]

**Comment by manuvarghese236** [comment]
please provide a link

**Comment by manuvarghese236** [comment]
Add status Column at end of the daysession Session table. and set the value to 1 (Enable)

--
-- Table structure for table `daysession`
--

CREATE TABLE `daysession` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `status` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `daysession`
--

INSERT INTO `daysession` (`id`, `name`, `status`) VALUES
(1, 'All Day', 1),
(2, 'Forenoon', 1),
(3, 'AfterNoon', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `daysession`
--
ALTER TABLE `daysession`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `daysession`
--
ALTER TABLE `daysession`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;COMMIT;
